#!/usr/bin/env bash
#
# gen-component-checksums.sh — regenerate the APK-side checksum manifest
# (app/app/src/main/assets/component_checksums.json) from scripts/assets.sha256.
#
# Run after scripts/refresh-checksums.sh whenever the component set changes.
#
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

python3 - "$REPO_ROOT/scripts/assets.sha256" "$REPO_ROOT/app/app/src/main/assets/component_checksums.json" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
data = {"_comment": "Pinned SHA-256 for every installable component. Generated by scripts/gen-component-checksums.sh from scripts/assets.sha256. Do not edit by hand."}
n = 0
for line in open(src):
    sha, path = line.split()
    if path.startswith("installable_components/"):
        data[path[len("installable_components/"):]] = sha
        n += 1
json.dump(data, open(dst, "w"), indent=2, sort_keys=True)
print("wrote %d component checksums -> %s" % (n, dst))
PY
